graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["API Application - Dynamic"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 20 [API Application]
      style 20 fill:#ffffff,stroke:#2e6295,color:#2e6295

      29["<div style='font-weight: bold'>Sign In Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Rest Controller]</div><div style='font-size: 80%; margin-top:10px'>Allows users to sign in to<br />the Internet Banking System.</div>"]
      style 29 fill:#85bbf0,stroke:#5d82a8,color:#000000
      32["<div style='font-weight: bold'>Security Component</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Bean]</div><div style='font-size: 80%; margin-top:10px'>Provides functionality<br />related to signing in,<br />changing passwords, etc.</div>"]
      style 32 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

    17["<div style='font-weight: bold'>Single-Page Application</div><div style='font-size: 70%; margin-top: 0px'>[Container: JavaScript and Angular]</div><div style='font-size: 80%; margin-top:10px'>Provides all of the Internet<br />banking functionality to<br />customers via their web<br />browser.</div>"]
    style 17 fill:#438dd5,stroke:#2e6295,color:#ffffff
    21[("<div style='font-weight: bold'>Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: Oracle Database Schema]</div><div style='font-size: 80%; margin-top:10px'>Stores user registration<br />information, hashed<br />authentication credentials,<br />access logs, etc.</div>")]
    style 21 fill:#438dd5,stroke:#2e6295,color:#ffffff

    17-. "<div>1. Submits credentials to</div><div style='font-size: 70%'>[JSON/HTTPS]</div>" .->29
    29-. "<div>2. Validates credentials<br />using</div><div style='font-size: 70%'></div>" .->32
    32-. "<div>3. select * from users where<br />username = ?</div><div style='font-size: 70%'>[JDBC]</div>" .->21
    21-. "<div>4. Returns user data to</div><div style='font-size: 70%'>[JDBC]</div>" .->32
    32-. "<div>5. Returns true if the hashed<br />password matches</div><div style='font-size: 70%'></div>" .->29
    29-. "<div>6. Sends back an<br />authentication token to</div><div style='font-size: 70%'>[JSON/HTTPS]</div>" .->17
  end