graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["D - F - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    3["<div style='font-weight: bold'>C</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 3 fill:#dddddd,stroke:#9a9a9a,color:#000000

    subgraph 6 [F]
      style 6 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      subgraph group1 [Group 4]
        style group1 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

        8["<div style='font-weight: bold'>H</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
        style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
      end

      7["<div style='font-weight: bold'>G</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>"]
      style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    3-. "<div></div><div style='font-size: 70%'></div>" .->7
    3-. "<div></div><div style='font-size: 70%'></div>" .->8
  end