@startuml
set separator none
title D - F - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System(C, "C", $descr="", $tags="", $link="")

Container_Boundary("D.F_boundary", "F", $tags="") {
  AddBoundaryTag("Group 5", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_1, "Group 5", $tags="Group 5") {
    Component(D.F.H, "H", $techn="", $descr="", $tags="", $link="")
  }

  Component(D.F.G, "G", $techn="", $descr="", $tags="", $link="")
}

Rel(C, D.F.G, "", $techn="", $tags="", $link="")
Rel(C, D.F.H, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml