@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Group 1", $borderColor="#111111", $fontColor="#111111", $borderStyle="dashed")
Boundary(group_1, "Group 1", $tags="Group 1") {
  Person(User1, "User 1", $descr="", $tags="", $link="")
}

AddBoundaryTag("Group 2", $borderColor="#222222", $fontColor="#222222", $borderStyle="dashed")
Boundary(group_2, "Group 2", $tags="Group 2") {
  Person(User2, "User 2", $descr="", $tags="", $link="")
}

AddBoundaryTag("Group 3", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_3, "Group 3", $tags="Group 3") {
  Person(User3, "User 3", $descr="", $tags="", $link="")
}



SHOW_LEGEND(true)
@enduml