@startuml
set separator none
title D - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(C, "C", $descr="", $tags="", $link="")

System_Boundary("D_boundary", "D", $tags="") {
  AddBoundaryTag("Group 3", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_1, "Group 3", $tags="Group 3") {
    Container(D.F, "F", $techn="", $descr="", $tags="", $link="")
  }

  Container(D.E, "E", $techn="", $descr="", $tags="", $link="")
}

Rel(C, D.E, "", $techn="", $tags="", $link="")
Rel(C, D.F, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml