@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #ffffff
  FontColor #cc2264
  BorderColor #cc2264
  roundCorner 20
}
rectangle "==Amazon Web Services - Auto Scaling\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/AWS-Auto-Scaling_light-bg@4x.png{scale=0.1}>" <<1>>

skinparam rectangle<<2>> {
  BackgroundColor #ffffff
  FontColor #232f3e
  BorderColor #232f3e
  roundCorner 20
}
rectangle "==Amazon Web Services - Cloud\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/AWS-Cloud_light-bg@4x.png{scale=0.21428571428571427}>" <<2>>

skinparam rectangle<<3>> {
  BackgroundColor #ffffff
  FontColor #d86613
  BorderColor #d86613
  roundCorner 20
}
rectangle "==Amazon Web Services - EC2\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Amazon-EC2_light-bg@4x.png{scale=0.1}>" <<3>>

skinparam rectangle<<4>> {
  BackgroundColor #ffffff
  FontColor #693cc5
  BorderColor #693cc5
  roundCorner 20
}
rectangle "==Amazon Web Services - Elastic Load Balancing\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Elastic-Load-Balancing_light-bg@4x.png{scale=0.1}>" <<4>>

skinparam rectangle<<5>> {
  BackgroundColor #ffffff
  FontColor #3b48cc
  BorderColor #3b48cc
  roundCorner 20
}
rectangle "==Amazon Web Services - RDS\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Amazon-RDS_light-bg@4x.png{scale=0.1}>" <<5>>

skinparam rectangle<<6>> {
  BackgroundColor #ffffff
  FontColor #3b48cc
  BorderColor #3b48cc
  roundCorner 20
}
rectangle "==Amazon Web Services - RDS MySQL instance\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Amazon-RDS_MySQL_instance_light-bg@4x.png{scale=0.15}>" <<6>>

skinparam rectangle<<7>> {
  BackgroundColor #ffffff
  FontColor #147eba
  BorderColor #147eba
  roundCorner 20
}
rectangle "==Amazon Web Services - Region\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Region_light-bg@4x.png{scale=0.21428571428571427}>" <<7>>

skinparam rectangle<<8>> {
  BackgroundColor #ffffff
  FontColor #693cc5
  BorderColor #693cc5
  roundCorner 20
}
rectangle "==Amazon Web Services - Route 53\n\n<img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/Amazon-Route-53_light-bg@4x.png{scale=0.1}>" <<8>>

skinparam rectangle<<9>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #b2b2b2
  roundCorner 20
}
rectangle "==Container, Application" <<9>>

skinparam database<<10>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #b2b2b2
}
database "==Container, Database" <<10>>

rectangle "." <<_transparent>> as 11
11 .[#707070,thickness=2].> 11 : "<color:#707070>Relationship"


@enduml