@startuml
set separator none
title A - Dynamic

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<A.A>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<B.B>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<A>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}
skinparam rectangle<<B>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

rectangle "A\n<size:10>[Software System]</size>" <<A>> {
  rectangle "Group 1" <<group1>> {
    skinparam RectangleBorderColor<<group1>> #cccccc
    skinparam RectangleFontColor<<group1>> #cccccc
    skinparam RectangleBorderStyle<<group1>> dashed

    rectangle "==A\n<size:10>[Container]</size>" <<A.A>> as A.A
  }

}

rectangle "B\n<size:10>[Software System]</size>" <<B>> {
  rectangle "Group 2" <<group2>> {
    skinparam RectangleBorderColor<<group2>> #cccccc
    skinparam RectangleFontColor<<group2>> #cccccc
    skinparam RectangleBorderStyle<<group2>> dashed

    rectangle "==B\n<size:10>[Container]</size>" <<B.B>> as B.B
  }

}

A.A .[#707070,thickness=2].> B.B : "<color:#707070>1. Uses"
@enduml