@startuml
set separator none
title System Landscape

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<A>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<B>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<C>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<D>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}

rectangle "Enterprise" <<enterprise>> {
  skinparam RectangleBorderColor<<enterprise>> #444444
  skinparam RectangleFontColor<<enterprise>> #444444

  rectangle "Group 2" <<group1>> {
    skinparam RectangleBorderColor<<group1>> #cccccc
    skinparam RectangleFontColor<<group1>> #cccccc
    skinparam RectangleBorderStyle<<group1>> dashed

    rectangle "==D\n<size:10>[Software System]</size>" <<D>> as D
  }

  rectangle "==C\n<size:10>[Software System]</size>" <<C>> as C
}

rectangle "Group 1" <<group2>> {
  skinparam RectangleBorderColor<<group2>> #cccccc
  skinparam RectangleFontColor<<group2>> #cccccc
  skinparam RectangleBorderStyle<<group2>> dashed

  rectangle "==B\n<size:10>[Software System]</size>" <<B>> as B
}

rectangle "==A\n<size:10>[Software System]</size>" <<A>> as A

B .[#707070,thickness=2].> C : "<color:#707070>"
C .[#707070,thickness=2].> D : "<color:#707070>"
A .[#707070,thickness=2].> B : "<color:#707070>"
@enduml