@startuml
set separator none
title System Landscape

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<User1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<User2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<User3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}

rectangle "Group 1\n\n<img:https://example.com/icon1.png{scale=1.0}>" <<group1>> as group1 {
  skinparam RectangleBorderColor<<group1>> #111111
  skinparam RectangleFontColor<<group1>> #111111
  skinparam RectangleBorderStyle<<group1>> dashed

  rectangle "==User 1\n<size:10>[Person]</size>" <<User1>> as User1
}

rectangle "Group 2\n\n<img:https://example.com/icon2.png{scale=1.0}>" <<group2>> as group2 {
  skinparam RectangleBorderColor<<group2>> #222222
  skinparam RectangleFontColor<<group2>> #222222
  skinparam RectangleBorderStyle<<group2>> dashed

  rectangle "==User 2\n<size:10>[Person]</size>" <<User2>> as User2
}

rectangle "Group 3" <<group3>> as group3 {
  skinparam RectangleBorderColor<<group3>> #aabbcc
  skinparam RectangleFontColor<<group3>> #aabbcc
  skinparam RectangleBorderStyle<<group3>> dashed

  rectangle "==User 3\n<size:10>[Person]</size>" <<User3>> as User3
}


@enduml