@startuml
set separator none
title System Landscape

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<Department1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Organisation1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Organisation2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Team1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Team2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}

rectangle "Organisation 1" <<group1>> as group1 {
  skinparam RectangleBorderColor<<group1>> #cccccc
  skinparam RectangleFontColor<<group1>> #cccccc
  skinparam RectangleBorderStyle<<group1>> dashed

  rectangle "==Organisation 1\n<size:10>[Software System]</size>" <<Organisation1>> as Organisation1
    rectangle "Department 1" <<group2>> as group2 {
      skinparam RectangleBorderColor<<group2>> #cccccc
      skinparam RectangleFontColor<<group2>> #cccccc
      skinparam RectangleBorderStyle<<group2>> dashed

      rectangle "==Department 1\n<size:10>[Software System]</size>" <<Department1>> as Department1
        rectangle "Team 1" <<group3>> as group3 {
          skinparam RectangleBorderColor<<group3>> #ff0000
          skinparam RectangleFontColor<<group3>> #ff0000
          skinparam RectangleBorderStyle<<group3>> dashed

          rectangle "==Team 1\n<size:10>[Software System]</size>" <<Team1>> as Team1
        }

        rectangle "Team 2" <<group4>> as group4 {
          skinparam RectangleBorderColor<<group4>> #0000ff
          skinparam RectangleFontColor<<group4>> #0000ff
          skinparam RectangleBorderStyle<<group4>> dashed

          rectangle "==Team 2\n<size:10>[Software System]</size>" <<Team2>> as Team2
        }

    }

}

rectangle "Organisation 2" <<group5>> as group5 {
  skinparam RectangleBorderColor<<group5>> #cccccc
  skinparam RectangleFontColor<<group5>> #cccccc
  skinparam RectangleBorderStyle<<group5>> dashed

  rectangle "==Organisation 2\n<size:10>[Software System]</size>" <<Organisation2>> as Organisation2
}


@enduml