@startuml
set separator none
title e - Dynamic

!pragma teoz true
skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<A.B.C>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.f>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.g>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.h>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}

box "A\n[Software System]"
    box "B\n[Container]"
      participant "C\n<size:10>[Component]</size>" as A.B.C <<A.B.C>> #dddddd
    box "d\n[Software System]"
        box "e\n[Container]"
          participant "f\n<size:10>[Component]</size>" as d.e.f <<d.e.f>> #dddddd
          participant "g\n<size:10>[Component]</size>" as d.e.g <<d.e.g>> #dddddd
          participant "h\n<size:10>[Component]</size>" as d.e.h <<d.e.h>> #dddddd
        d.e.f -[#707070]> d.e.h : 
        A.B.C -[#707070]> d.e.f : 
        d.e.f -[#707070]> d.e.g : 
        @enduml